k8s-dashboard: Fix build break by using a specific version of closure-library
kubernetes-dashboard is failing to build as shown below:

[10:06:10] gulp-google-closure-compiler: base.js:1950:
WARNING - Parse error. unknown @suppress parameter: strictMissingProperties
 * @suppress {strictMissingProperties} superClass_ and base is not defined on
              ^

base.js:2040: ERROR - unknown type: symbol
  if (typeof opt_methodName != 'string' && typeof opt_methodName != 'symbol') {
                                                                    ^^^^^^^^

1 error(s), 1 warning(s), 94.7% typed

[10:06:10] 'scripts:prod' errored after 26 s
[10:06:10] Error in plugin 'gulp-google-closure-compiler'
Message:
    Compilation error


The build script pulls down google-closure-library from github as a
dependency. However, since no particular version is specified, it gets
the latest commit (HEAD), which doesn't pass the build at the moment.
Fix this by pulling down a specific version that is known to work.

Change-Id: I72648ba42277448b2c6b6e374a9e5d08623b4327