91/92: linux: remove linux requires from linux-tools
If there is a mismatch between running kernel version and linux-tools,
users should resolve it manually; this is not a concern because
linux-tools is mostly a developer tool.

This is done to prevent %prein failues during linux-tools installation
in chroot. Reason being: bash getting installed after linux.

toybox provindes minimal implementation of /bin/sh
libsolv assumes /bin/sh is sufficient and installs it early

-> toybox gets installed before linux
-> linux gets installed soon after toybox (results in prein failure)
-> bash gets installed later
And rpm transaction is marked as failure ultimately.

Logs:
```
root@ph5dev [ ~ ]# tdnf --releasever 5.0 --installroot $PWD/t install -y filesystem bash linux-tools toybox
...
...
Running transaction
Installing/Updating: filesystem-1.1-11.ph5.x86_64
warning: group mail does not exist - using root
Installing/Updating: bash-bin-5.3-1.ph5.x86_64
Installing/Updating: openssl-libs-3.5.7-4.ph5.x86_64
Installing/Updating: glibc-2.43-6.ph5.x86_64
Installing/Updating: glibc-libs-2.43-6.ph5.x86_64
Installing/Updating: zlib-1.3.2-1.ph5.x86_64
Installing/Updating: libxcrypt-4.5.2-2.ph5.x86_64
Installing/Updating: toybox-0.8.9-16.ph5.x86_64   ====> toybox got installed here
Installing/Updating: ncurses-libs-6.6-1.ph5.x86_64
Installing/Updating: readline-8.3-1.ph5.x86_64
...
...
Installing/Updating: shadow-4.13-14.ph5.x86_64
error: %prein(linux-6.12.103-5.ph5.x86_64) scriptlet failed, exit status 1
package linux-6.12.103-5.ph5.x86_64: script error in %prein
error: linux-6.12.103-5.ph5.x86_64: install failed
Installing/Updating: python3-3.14.7-1.ph5.x86_64
...
...
Installing/Updating: linux-tools-6.12.103-5.ph5.x86_64
Installing/Updating: bash-5.3-1.ph5.x86_64        ====> bash got installed here
Error(1525) : rpm transaction failed
```

Change-Id: I4a610f6bf22406f55cf9b278bfc862445965a2b6
Signed-off-by: Shreenidhi Shedi <shreenidhi.shedi@broadcom.com>
Reviewed-on: http://photon-gerrit.lvn.broadcom.net/c/photon/+/28535
Reviewed-by: Vamsi Krishna Brahmajosyula <vamsi-krishna.brahmajosyula@broadcom.com>
Reviewed-by: Tapas Kundu <tapas.kundu@broadcom.com>