kernels: Add mlx5 support
Requested by GPU Driver VM.

After enabling CONFIG_MLX5_ESWITCH=y, linux-esx build starts to fail with
ERROR: modpost: "mlx5_eswitch_reload_ib_reps" [drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko] undefined!
Narrowed down to CVE/0003-net-mlx5-Reload-only-IB-representors-upon-lag-disabl.patch
Which replaces all invocations to mlx5_eswitch_reload_reps() into
mlx5_eswitch_reload_ib_reps(), while keeping the function definition as is with
no changes! Surprisingly generic linux uses the same patch, but compiles fine.
But it fails at runtime on "modprobe mlx5_core" with an error:
mlx5_core: Unknown symbol mlx5_eswitch_reload_ib_reps (err -2)
Added missing patch chunk back from original upsteram patch.

While looking at drivers/net/ethernet list, I found multiple =y options
which bloat the kernel size, but were never requested by any linux-esx
consumers. Probably were accidentally enabled while bumping up from one
LTS version to another. Disable them.

Change-Id: I4a58cf821214bbb2cae8a7880b7da83114a6a3cc
Fixes: 5eb21605a9491753 ("kernels: Fixes multiple CVEs")
Signed-off-by: Alexey Makhalov <alexey.makhalov@broadcom.com>
Reviewed-on: http://photon-gerrit.lvn.broadcom.net/c/photon/+/26768
Reviewed-by: Brennan Lamoreaux <brennan.lamoreaux@broadcom.com>
Reviewed-by: Bo Gan <bo.gan@broadcom.com>
Tested-by: gerrit-photon <svc.photon-ci@broadcom.com>
Reviewed-by: gerrit-photon <svc.photon-ci@broadcom.com>