Added setuptools in requires for python-sphinx
sphinx is throwing the below error in 2.0

root@photon-2 [ ~ ]# sphinx-quickstart --help
Traceback (most recent call last):
  File "/usr/bin/sphinx-quickstart", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
root@photon-2 [ ~ ]

It requires python-setuptools in requires to work.

Hence, added this change.

Change-Id: Ieb41733f8038924dbfc361c8f0a4048aa6a9fddc
Signed-off-by: Tapas Kundu <tkundu@vmware.com>
Reviewed-on: http://photon-jenkins.eng.vmware.com:8082/7057
Reviewed-by: Anish Swaminathan <anishs@vmware.com>