systemtap: Updated to 4.4 to fix pkg test
- systemtap pkg test is passing without compilation errors

Change-Id: I606b31e8acfc9f8cd6c393eac0261137a002c5fc
Reviewed-on: http://photon-jenkins.eng.vmware.com:8082/11723
Tested-by: gerrit-photon <photon-checkins@vmware.com>
Reviewed-by: Tapas Kundu <tkundu@vmware.com>