tuned: fix dbus conf rules loading issue
Issue:
After installing the dbus conf rules, dbus doesn't load them automatically
and subsequent start of the service fails with following error
'''
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.22" is not allowed to own the service "com.redhat.tuned" due to security policies in the configuration file
'''
Fix:
Relaod the dbus conf rules using below command:
`killall -HUP dbus-daemon`

Change-Id: Ic043b13e4aaa74fa629ec3d7783b180af6aa5861
Signed-off-by: Ankit Jain <ankit-aj.jain@broadcom.com>
Reviewed-on: http://photon-jenkins.eng.vmware.com:8082/c/photon/+/23961
Tested-by: gerrit-photon <photon-checkins@vmware.com>
Reviewed-by: Shreenidhi Shedi <shreenidhi.shedi@broadcom.com>