linux: canister: removed unknown symbol from canister
- During canister consumption, found following issue:
```
undefined reference to `__SCT__cond_resched'
```
- Fixed using the canister wrapper api
Extras:
- Removed "approved/non-approved" prints which were
 left in aesni-intel_glue.c

Fixes: https://github.com/vmware/photon/commit/6f88139e42507313d3b6347766e75ae0877f163f
Fixes: https://github.com/vmware/photon/commit/48d76889c0bfd038dc12a2c56b29382d204e406a
Change-Id: I3701dac685e44db9df05d6cd113d0ac41ccd7fc7
Signed-off-by: Ankit Jain <ankit-aj.jain@broadcom.com>
Reviewed-on: http://photon-gerrit.lvn.broadcom.net/c/photon/+/26644
Reviewed-by: Brennan Lamoreaux <brennan.lamoreaux@broadcom.com>
Reviewed-by: gerrit-photon <svc.photon-ci@broadcom.com>
Reviewed-by: Srinidhi Rao <srinidhi.rao@broadcom.com>
Tested-by: gerrit-photon <svc.photon-ci@broadcom.com>