photon-os-installer: Added a none check while parsing df
- In old version of df, column data maybe unalign, which
causes error while jc parsing as below:
```
df = [d for d in df if d['mounted_on'].startswith(self.photon_root)]
AttributeError: 'NoneType' object has no attribute 'startswith'
```
Fixes this by adding a null check

Change-Id: Ic79c39009be36d3bf8281348883026a46fccd9b6
Signed-off-by: Ankit Jain <ankit-aj.jain@broadcom.com>
Reviewed-on: http://photon-jenkins.eng.vmware.com:8082/c/photon/+/24497
Tested-by: gerrit-photon <photon-checkins@vmware.com>
Reviewed-by: Keerthana K <keerthana.kalyanasundaram@broadcom.com>
Reviewed-by: Dweep Advani <dweep.advani@broadcom.com>