python-pyOpenSSL: Downgrade to v22.0.0
- Due to an upstream issue
https://github.com/pyca/pyopenssl/issues/1154
 downgrading the version to v22.0.0
- This fixes the issue during installation time
"ERROR: deprecated() got an unexpected keyword argument 'name'"

Change-Id: I694e3c4366c2455c683878271ff0079b601327be
Signed-off-by: Ankit Jain <ankitja@vmware.com>
Reviewed-on: http://photon-jenkins.eng.vmware.com:8082/18672
Tested-by: Michelle Wang <michellew@vmware.com>
Reviewed-by: Tapas Kundu <tkundu@vmware.com>