gcc: update to 6.3
Fix gcc-6.3 compilation error for:
- logrotate
- xml-security-c
- thin-provisioning-tools
- ipxe: version update

Change-Id: I6ab46e74bbff7b9cd9d493ca13106a6be01910c0
Reviewed-on: http://photon-jenkins.eng.vmware.com:8082/2135
Tested-by: gerrit-photon <photon-checkins@vmware.com>
Reviewed-by: Vinay Kulkarni <kulkarniv@vmware.com>