libyang: update to 2.1.55, resolve CVEs
Update libyang to 2.1.55 to resolve two CVEs:
    CVE-2023-26917
    CVE-2023-26916

Version bump for libnetconf2 and frr since they are dependent on libyang.

frr: Added a patch to link libabsl_synchronization library,
     otherwise I was running into compilation errors with test_grpc.
     Also - modified patch to skip grpc to check specifically for
     frr yang files.

libnetconf2: make check was failing - %{__cmake_builddir}/tests/data
             doesn't seem to exist, and neither does 'build' dir.
             So modified check section to avoid this.

libyang:    Skip valgrind tests, since logs indicate that glibc-debuginfo
            package is needed and we can't install that into buildroot.

Change-Id: I77580939fde100bb311188ad80cb19a9dcf6ed02
Reviewed-on: http://photon-jenkins.eng.vmware.com:8082/20530
Tested-by: gerrit-photon <photon-checkins@vmware.com>
Reviewed-by: Shreenidhi Shedi <sshedi@vmware.com>